services:
  uvicorn:
    build: .
    ports:
      - "8444:8444"  # Uvicorn
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c ". /venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8444"
    restart: unless-stopped
    mem_limit: 1g  # Ограничение памяти
